runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: https://aiabotpython.herokuapp.com/
  script: bot_gae.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: ssl
version: latest
